# Generated by Django 4.0.6 on 2022-07-21 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='update',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='folderuserpermissions',
            old_name='update',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='projectuserpermissions',
            old_name='update',
            new_name='updated',
        ),
    ]
