# Generated by Django 4.0.6 on 2022-07-24 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editor', '0002_rename_update_folder_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='users',
            field=models.ManyToManyField(related_name='folders', through='editor.FolderUserPermissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='folder',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_folders', to=settings.AUTH_USER_MODEL),
        ),
    ]
