# Generated by Django 4.0.6 on 2022-07-24 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_folder_users_alter_folder_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='editor.folder'),
        ),
    ]
