# Generated by Django 4.0.6 on 2022-09-21 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import editor.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editor', '0005_sourcefile_mediafile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ver', editor.fields.OrderField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('committed', models.BooleanField(default=False)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='editor.sourcefile')),
            ],
            options={
                'ordering': ['ver'],
            },
        ),
        migrations.CreateModel(
            name='VersionsRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='older_versions', to='editor.fileversion')),
                ('older', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newer_versions', to='editor.fileversion')),
            ],
        ),
        migrations.AddField(
            model_name='fileversion',
            name='previous_versions',
            field=models.ManyToManyField(through='editor.VersionsRelation', to='editor.fileversion'),
        ),
        migrations.CreateModel(
            name='FileChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('value', models.TextField()),
                ('order', editor.fields.OrderField(blank=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'insertion'), (2, 'removal'), (3, 'replace')])),
                ('file_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='editor.fileversion')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committed_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
