# Generated by Django 4.0.6 on 2022-09-22 11:17

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0006_fileversion_versionsrelation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileversion',
            options={'ordering': ['-ver']},
        ),
        migrations.AddField(
            model_name='mediafile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 9, 22, 11, 17, 3, 146734, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sourcefile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
