# Generated by Django 4.0.6 on 2022-10-25 13:39

from django.db import migrations, models
import django.db.models.deletion
import editor.models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0007_alter_fileversion_options_mediafile_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompiledFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=editor.models.result_file_project_path)),
                ('log_file', models.FileField(upload_to=editor.models.result_file_project_path)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compiled_files', to='editor.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sourcefile',
            name='compiled_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='editor.compiledfile'),
        ),
    ]
