# Generated by Django 4.0.6 on 2022-11-15 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0009_project_uuid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectTag',
        ),
    ]
